Enable debuginfod on images
pulp/pulp-oci-images pull request #212
Opened 2022-06-23 11:01 UTC by fao89

2022-06-23 16:27 UTC, RyanSGoldberg requested changes
This looks good on my end. I just added in a quick fix to include the DEBUGINFOD_OPTIONS in the start script

2022-06-23 16:27 UTC, RyanSGoldberg commented on assets/start_script.sh
> +debuginfod -R /var/lib/pulp -Z=cat  & /init
```suggestion
debuginfod -R /var/lib/pulp -Z=cat $1 & /init
```

2022-06-23 16:27 UTC, RyanSGoldberg commented on pulp/Containerfile
> +ARG DEBUGINFOD_OPTIONS=""
```suggestion
ARG DEBUGINFOD_OPTIONS=""
ENV DEBUGINFOD_ENV=$DEBUGINFOD_OPTIONS
```

2022-06-23 16:27 UTC, RyanSGoldberg commented on pulp_ci_centos/Containerfile
```suggestion
RUN chmod +x /start_script.sh
```

2022-06-23 16:27 UTC, RyanSGoldberg commented on pulp_ci_centos/Containerfile
> +ENTRYPOINT ["/start_script.sh"]
```suggestion
# ARGs are not expanded in entry point, while ENV will be by the shell
ENV DEBUGINFOD_ENV=""
ENTRYPOINT /start_script.sh "${DEBUGINFOD_ENV}"
```

2022-06-23 16:27 UTC, RyanSGoldberg commented on pulp_galaxy_ng/Containerfile
```suggestion
ENV DEBUGINFOD_ENV=$DEBUGINFOD_OPTIONS
```

2022-07-25 10:32 UTC, mdellweg commented
I don't know, why i am tagged for review, but let's start and ask the nasty questions:
What kind of problem is this PR solving?
How can debuginfod help us? (sounds to me that it helps with elf targets, how is it helpful for python?)
Is running debuginfod not driving us away from the goal of making the OCI images ready for production?

2022-07-25 10:39 UTC, fche commented
> What kind of problem is this PR solving? 

It lets pulp operators share the debuginfo/debugsource content pulp downloaded with nearby users, so they don't have to do sudo yum etc. operations.

> How can debuginfod help us? (sounds to me that it helps with elf targets, how is it helpful for python?) 

It's neutral for pulp installations that redistribute python packages/rpms, except that debugging those python packages that carry native code shared libraries (and the python VM itself) become more easily debuggable.

> Is running debuginfod not driving us away from the goal of making the OCI images ready for production?

In what way?

2022-09-29 18:10 UTC, closed without merging