docker-compose: Env vars for custom storage paths
pulp/pulp-oci-images pull request #410
Opened 2023-01-11 15:14 UTC by jlsherrill

2023-01-11 20:31 UTC, mikedep333 requested changes

2023-01-11 20:31 UTC, mikedep333 commented on images/compose/README.md
> +PULP_STORAGE_PATH="./storage" PULP_DATABASE_PATH="./database" podman-compose -f docker-compose.folders.yml up
Document PULP_POSTGRES_PATH too?

2023-01-11 21:11 UTC, jlsherrill commented on images/compose/README.md
> +PULP_STORAGE_PATH="./storage" PULP_DATABASE_PATH="./database" podman-compose -f docker-compose.folders.yml up
documented my own option incorrectly :)

2023-01-11 21:11 UTC, jlsherrill commented on images/compose/README.md
> +PULP_STORAGE_PATH="./storage" PULP_DATABASE_PATH="./database" podman-compose -f docker-compose.folders.yml up
fixed

2023-01-13 21:00 UTC, jlsherrill commented
as part of our integration, we don't actually need this anymore.  Feel free to close this or merge it :)

2023-02-03 20:50 UTC, mikedep333 commented
Thank you, but I honestly don't think this is needed. I doubt fixed folder names will be a problem for users.

2023-02-03 20:50 UTC, closed without merging