Add pulp_ostree to the stable image
pulp/pulp-oci-images pull request #464
Opened 2023-03-21 16:46 UTC by lubosmj

[noissue]

2023-03-21 16:47 UTC, lubosmj commented
@pulp/infrastructure, is this everything I should do in order to make pulp_ostree GA in the stable container?

2023-03-30 15:00 UTC, mikedep333 approved these changes

2023-03-30 15:06 UTC, mikedep333 requested changes

2023-03-30 15:06 UTC, mikedep333 commented on images/pulp-minimal/stable/Containerfile.core
>    pulp-rpm${PULP_RPM_VERSION} && \
Remove the && here.

2023-03-30 15:55 UTC, mikedep333 approved these changes

2023-03-30 16:15 UTC, merged