Add a default settings.py file for galaxy
pulp/pulp-oci-images pull request #478
Opened 2023-05-11 06:08 UTC by newswangerd

This adds a default settings.py file to the galaxy image that allows for galaxy_ng to be run out of the box with very little configuration. The goal of this PR is to make the galaxy image as simple as possible for anyone to take for a spin.

```
# run galaxy on localhost
docker run -p 5001:80  ghcr.io/pulp/galaxy:latest

# run galaxy on localhost with https
docker run -p 443:443 -e "PULP_HTTPS=true" -e "GALAXY_PORT=443"  ghcr.io/pulp/galaxy:latest

# run galaxy from a server with https
docker run -p 443:443 -e "PULP_HTTPS=true" -e "GALAXY_PORT=443" -e "GALAXY_HOSTNAME=192.168.0.100"  ghcr.io/pulp/galaxy:latest

# modify the system settings to allow for uploads without approval
docker run -p 5001:80  -e "PULP_GALAXY_REQUIRE_CONTENT_APPROVAL=false" ghcr.io/pulp/galaxy:latest
```

[noissue]

2023-05-11 15:01 UTC, mikedep333 requested changes

2023-05-11 15:01 UTC, mikedep333 commented on images/galaxy/nightly/Containerfile
> +COPY images/galaxy/settings.py /etc/pulp/settings.py
I just realized this.

Our instructions are to mount the `settings` directory. Which will include generated certificates, that must be preserved.

However, if we mount the `settings` directory, this file will be ignored.

Users can work around this by pre-creating (mkdir -p) and mounting the `settings/certs` subdir instead:

2023-05-11 15:43 UTC, mikedep333 commented on docs/multi-process-images.md
>  1st, create the directories for storage/configuration, and create the `settings.py` file:
Replace:
```
$ mkdir settings pulp_storage pgsql containers
```
with:
```
$ mkdir -p settings/certs pulp_storage pgsql containers
```

2023-05-30 16:21 UTC, mikedep333 requested changes

2023-05-30 16:21 UTC, mikedep333 commented on docs/multi-process-images.md
> +             --volume "$(pwd)/certs":/etc/pulp/certs:Z \
```suggestion
             --volume "$(pwd)/settings/certs":/etc/pulp/certs:Z \
```

2023-06-29 20:28 UTC, newswangerd commented
@mikedep333 finally got around to updating this

2023-07-13 15:03 UTC, mikedep333 approved these changes

2023-07-13 15:05 UTC, merged