Install python3-createrepo_c and remove its build needs.
pulp/pulp-oci-images pull request #507
Opened 2023-06-14 19:06 UTC by decko

Closes #506

2023-06-14 19:08 UTC, dralley commented on images/Containerfile.core.base
>  RUN dnf -y install python38 python38-cryptography python38-devel && \
Can probably delete the comments above

2023-06-14 19:08 UTC, dralley approved these changes

2023-06-14 19:25 UTC, mikedep333 requested changes

2023-06-14 19:25 UTC, mikedep333 commented on images/Containerfile.core.base
> +    dnf -y install --setopt=install_weak_deps=False python3-createrepo_c && \
Wait, isn't createrepo_c in the virtualenv rather than in the OS?

If so, we need the build dependencies for this, rather than the package itself.

2023-06-14 19:29 UTC, mikedep333 requested changes

2023-06-14 19:29 UTC, mikedep333 commented on images/Containerfile.core.base
> +    dnf -y install --setopt=install_weak_deps=False libcurl-devel libxml2-devel sqlite-devel file-devel && \
All of these are build deps for createrepo_c

2023-06-20 18:25 UTC, dralley commented
See comment here: https://github.com/pulp/pulp-oci-images/issues/506#issuecomment-1599291716

I don't think we can stop using the python package built from source unless we upgrade the base image to CentOS 9 stream.

2023-08-29 19:54 UTC, closed without merging