Configure SSL if variable is capitalized or not
pulp/pulp-oci-images pull request #553
Opened 2023-09-27 08:51 UTC by tinsjourney

When using ansible-podman-collections to create the multi-process images, boolean environment are capitalized.
So this is workaround until
https://github.com/containers/ansible-podman-collections/issues/648 is fixed.

2023-09-27 10:16 UTC, mdellweg requested changes

2023-09-27 10:16 UTC, mdellweg commented on images/s6_assets/init/nginx
> +if [[ "${PULP_HTTPS}" = "true" || "${PULP_HTTPS}" = "True" ]]; then
```suggestion
if [ "${PULP_HTTPS,,}" = "true" ]; then
```
I am +1 for making the matching less strict.
But you should probably not define your environment variables with bool in the first place.
Yaml does not like Norway...

2023-09-27 21:19 UTC, mdellweg commented
Instead of closing, the PR, would you be willing to apply the suggestion and we can merge it?

2023-09-28 07:38 UTC, tinsjourney commented
@mdellweg OK I reopened the PR and did the change.

2023-09-28 09:19 UTC, mdellweg approved these changes

2023-09-29 12:31 UTC, mdellweg commented
Can you please squash to commits into one?

2023-10-04 15:00 UTC, merged